import assert from "node:assert/strict";
import {
  compiledPack,
  detect,
  engine,
  firstField,
  partNumberPnJson,
  resourceEntries,
  skhynixH25RawInternalExtra,
  skhynixHn8RuleIds,
  assertDecodePackDieProfile,
  assertDecodedPartNumber,
  assertDieProfileFromFdbProcess,
  assertFdbDoesNotOverrideDecodePackFields,
  assertFieldBlock,
  assertHiddenComponentRelations,
  assertHiddenPublicField,
  assertIdentifierRelation,
  assertKioxiaManagedRuleMatches,
  assertKioxiaRawSuffixTopology,
  assertMicronDecodePackDieProfile,
  assertMicronManagedFbgaMarking,
  assertNoAdditionalFields,
  assertNotFound,
  assertRuleDecode,
  assertRuleDoesNotMatch,
  assertRuleDraftDieProfile,
  assertSearchPnFirst,
  assertSearchPnIncludes,
  assertSkhynixEmcpRuleMatches,
  assertSkhynixHn8RuleMatches,
  assertSubtitle
} from "./_helpers";

const micronUmcpVoltage = {
  q: "LPDRAM VDD/VDDQ: 1.1V/0.6V; UFS VCC/VCCQ: 3.3V/1.8V",
  s: "LPDRAM VDD/VDDQ: 1.1V/0.6V; UFS VCC/VCCQ: 2.5V/1.2V",
  t: "LPDRAM VDD/VDDQ: 1.05V/0.5V; UFS VCC/VCCQ: 2.5V/1.2V"
};

for (const sample of [
  {
    partNumber: "MT29VZZZAD8HQKWL 053 W.G8C",
    densityMbit: 524288,
    storageDensity: "64GB UFS",
    dramDensity: "32Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2750 100s v2.1",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-3733",
    dieRevision: "G8C",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZBDAFQKWL 046 W.G0J",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "48Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "G0J",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZBDAFQKBA 046 W.G0J",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "48Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "G0J",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZCDAFQKWL 046 W.G0L",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "G0L",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZCDAFQKBA 046 W.G0L",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "G0L",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZAD9FQFSM 046 W.G9K",
    densityMbit: 1048576,
    storageDensity: "128GB UFS",
    dramDensity: "32Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "2 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "G9K",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZ7D8FQFSL 046 W.11K",
    densityMbit: 524288,
    storageDensity: "64GB UFS",
    dramDensity: "24Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "2 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "11K",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZAD8FQKSL 046 W.12H",
    densityMbit: 524288,
    storageDensity: "64GB UFS",
    dramDensity: "32Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2752 110s v2.1/v2.2",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "12H",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZBD91SLSM 046 W.17X",
    densityMbit: 1048576,
    storageDensity: "128GB UFS",
    dramDensity: "48Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.s,
    controller: "SM2754 140s v2.2",
    packageConfiguration: "3 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "17X",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZCD91SKSM 046 W.17Y",
    densityMbit: 1048576,
    storageDensity: "128GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.s,
    controller: "SM2754 140s v2.2",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "17Y",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZCD91SFSM 046 W.18C",
    densityMbit: 1048576,
    storageDensity: "128GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.s,
    controller: "SM2754 140s v2.2",
    packageConfiguration: "2 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "18C",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZ7D81SFSL 046 W.22B",
    densityMbit: 524288,
    storageDensity: "64GB UFS",
    dramDensity: "24Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.s,
    controller: "SM2754 140s v2.2",
    packageConfiguration: "2 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "22B",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZAD81SFSL 046 W.22C",
    densityMbit: 524288,
    storageDensity: "64GB UFS",
    dramDensity: "32Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.s,
    controller: "SM2754 140s v2.2",
    packageConfiguration: "2 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-4266",
    dieRevision: "22C",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT30AZZZCD9ZTOQS 031 W.15Q",
    densityMbit: 1048576,
    storageDensity: "128GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "SM2754 120s v3.1",
    packageConfiguration: "6 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "48Gb (4 x Y2BM) + 16Gb (2 x Y21N)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "15Q",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZCDAZTPWL 031 W.16C",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "SM2754 120s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "64Gb (8 x Y31N)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "16C",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZCDBZTPEQ 031 W.16D",
    densityMbit: 4194304,
    storageDensity: "512GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "SM2754 120s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "64Gb (8 x Y31N)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "16D",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZDDA0TPQS 031 W.19Q",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "96Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "9U6A 140s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "96Gb (8 x Y2BM)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "19Q",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZDDA0TPQS 026 W.19Q",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "96Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "9U6A 140s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "96Gb (8 x Y2BM)",
    dramSpeed: "LPDDR5-8533",
    dieRevision: "19Q",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZDDA0TPQS 031 WL.19Q",
    densityMbit: 2097152,
    storageDensity: "256GB UFS",
    dramDensity: "96Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "9U6A 140s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "96Gb (8 x Y2BM)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "19Q",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZDDB0TPWL 031 W.19R",
    densityMbit: 4194304,
    storageDensity: "512GB UFS",
    dramDensity: "96Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "9U6A 140s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "96Gb (8 x Y2BM)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "19R",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZDDB0TPWL 031 WL.19R",
    densityMbit: 4194304,
    storageDensity: "512GB UFS",
    dramDensity: "96Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "9U6A 140s v3.1",
    packageConfiguration: "8 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramConfiguration: "96Gb (8 x Y2BM)",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "19R",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT30AZZZCDB0TKWL 031 W.20X",
    densityMbit: 4194304,
    storageDensity: "512GB UFS",
    dramDensity: "64Gb",
    dramType: "LPDDR5",
    voltage: micronUmcpVoltage.t,
    controller: "9U6A 140s v3.1",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-297",
    dramSpeed: "LPDDR5-6400",
    dieRevision: "20X",
    productMode: "UFS + Mobile LPDDR5"
  },
  {
    partNumber: "MT29VZZZ7D7HQKWL 062 W.G7A",
    densityMbit: 262144,
    storageDensity: "32GB UFS",
    dramDensity: "24Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2750 100s v2.1",
    packageConfiguration: "4 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-3200",
    dieRevision: "G7A",
    productMode: "UFS + Mobile LPDDR4X"
  },
  {
    partNumber: "MT29VZZZBD8HQOWL 053 W.G8D",
    densityMbit: 524288,
    storageDensity: "64GB UFS",
    dramDensity: "48Gb",
    dramType: "LPDDR4X",
    voltage: micronUmcpVoltage.q,
    controller: "SM2750 100s v2.1",
    packageConfiguration: "6 LPDRAM, 1 UFS",
    package: "uMCP-254",
    dramSpeed: "LPDDR4X-3733",
    dieRevision: "G8D",
    productMode: "UFS + Mobile LPDDR4X"
  }
] as const) {
  assertRuleDecode(sample.partNumber, {
    vendor: "micron",
    type: "uMCP",
    densityMbit: sample.densityMbit,
    voltage: sample.voltage,
    package: sample.package,
    extra: {
      "Storage Density": sample.storageDensity,
      "Storage Interface": "UFS",
      "Controller": sample.controller,
      "DRAM Density": sample.dramDensity,
      ...("dramConfiguration" in sample ? { "DRAM Configuration": sample.dramConfiguration } : {}),
      "DRAM Type": sample.dramType,
      "DRAM Width": "x32",
      "Package Configuration": sample.packageConfiguration,
      "DRAM Speed": sample.dramSpeed,
      "Operation Temperature": "Wireless (-25°C ~ 85°C)",
      "Die Revision": sample.dieRevision
    },
    absentExtra: ["Config Code", "Package Code", "Controller Code", "Product Mode", "Product Family", "Speed Grade"]
  });
}

assertHiddenPublicField("MT29VZZZCD91SFSM 046 W.18C", "density", 1048576);
assertHiddenComponentRelations("MT29VZZZCD91SFSM 046 W.18C");

for (const partNumber of ["MT29VZZZBDAFQKWL 046 W.G0J", "MT30AZZZCD9ZTOQS 031 W.15Q"]) {
  assertNoAdditionalFields(partNumber);
}
